[package]
name = "crunch-gd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crunch = "0.3.3"
clap = "2.33.0"
image = "0.24.4"
glob = "0.3.0"
path-slash = "0.2.1"